config/routes.rb
Rails.application.routes.draw do

  #get 'users/root'
  resources :checkins, except: [:index]
  resources :checkouts, except: [:index, :show]

  get 'schools/' => 'schools#_index', :as => 'schools'
  resources :schools, except: [:index]

  get 'supers/' => 'supers#_index', :as => 'supers'
  resources :supers, except: [:index]
  #Routes to delete all data from all checkins and checkouts table
  get '/supers/:id/cleandb', to: 'supers#cleandb',:as=> "cleandb"

  get 'admins/' => 'admins#_index', :as => 'admins'
  resources :admins, except: [:index]

  # for signed-in-user main page

  get 'mentors/' => 'mentors#_index', :as => 'mentors'
  get 'mentors/new' => 'mentors#new', :as => 'new_mentor'
  get 'mentors/:id' => 'mentors#appointment', :as => 'mentor'
  get 'mentors/:id/details' => 'mentors#show', :as => 'mentor_details'
  get 'mentors/:id/attendances' => 'mentors#attendances', :as => 'mentor_attendances'
  resources :mentors, except: [:index, :show, :new]

  #for check in and checkout @Raj
  get 'mentors/:id/get_loc', to: "mentors#get_loc"
  get '/mentors/:id/checkin', to: 'mentors#checkin', as: 'mentor_checkin'
  get '/mentors/:id/checkout', to: 'mentors#checkout', as: 'mentor_checkout'
  get '/mentors/:id/checkin_loc', to: 'mentors#checkin_loc', as: 'mentor_checkin_loc'
  get '/mentors/:id/checkout_loc', to: 'mentors#checkout_loc', as: 'mentor_checkout_loc'

  root :to => 'logins#new'

  # for google_sign_in checks
  get 'login', to: 'logins#new'
  get 'login/create', to: 'logins#create', as: :create_login

  # for log out
  delete '/logout',  to: 'logins#destroy'
  resource :session

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/mentor.rb
class Mentor < ApplicationRecord

  belongs_to :school
  has_many :checkins, dependent: :destroy
  has_many :checkouts, dependent: :destroy

  before_save {self.email = email.downcase}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :name, presence: true, length: {minimum: 3, maximum: 60}
  validates :email, presence: true, uniqueness: {case_sensitive: false},
            length: {maximum: 320}, format: {with: VALID_EMAIL_REGEX}

  # return a list of attendences of the mentor in the specific week
  # where an attendence is a hash containing
  # {school_name, date, duration, forgot_checkout, isValid, checkin, checkout}

  def attendances(week_date)
     result = []
     self.checkins.each do |checkin|
        checkin_time = checkin.checkin_time
        if same_week?(checkin_time, week_date)
            date = checkin_time.strftime("%m/%d/%Y")
            school_name = checkin.school.name
            checkout = checkin.correspond_checkout
            forgot_checkout = checkout.nil?
            isValid = checkin.isValid && (checkout.nil? ? true : checkout.isValid)
            duration = duration_length(checkin, checkout)
            result.push({school_name:school_name,
                        date:date, duration:duration,
                        forgot_checkout: forgot_checkout,
                        isValid: isValid,
                        checkin:checkin, checkout:checkout})
        end
     end
     result
  end

  # return whether timeA and timeB are in the same week
  def same_week?(timeA, timeB)
    if timeA >= timeB.beginning_of_week && timeA <= timeB.end_of_week
      true
    else
      false
    end
  end

  # return the duration between a checkin and a checkout in hours
  def duration_length(checkin, checkout)
    duration = 0
    unless checkout.nil?
        duration = (checkout.checkout_time - checkin.checkin_time) / 1.hour
        duration = duration.round(2)
    end
    duration
  end

  # return the totalhours = {week_date, school_name, num_hours, forgot_checkout, anyInvalid}
  # for the mentor in the specific week
  # Assuming each mentor is associated with only one school.
  # Otherwise, many-to-many association would require an argument "school_id" to specify which school
  # Assuming the mentor only check in at one school in a week, even though mentors can be reassigned to different school

  def totalhours(week_date)
    num_hours = 0
    school_name = nil
    forgot_checkout = false
    anyInvalid = false
    self.attendances(week_date).each do |attend|
        school_name = attend[:school_name]
        num_hours += attend[:duration] if attend[:isValid]
        forgot_checkout = true if attend[:forgot_checkout]
        anyInvalid = true unless attend[:isValid]
    end
    week_date = week_date.beginning_of_week.strftime("%m/%d/%Y")
    {week_date: week_date,
      school_name: school_name,
      num_hours: num_hours,
      forgot_checkout: forgot_checkout,
      anyInvalid: anyInvalid}
  end

  # return the weeks summary of the mentor (total hours, etc) for every week
  def weeks_summary
    summary =[]
    if self.checkins.count > 0
      first_week = self.first_week
      week_date = Time.current
      while week_date >= first_week do
        summary.push(totalhours(week_date))
        week_date = week_date.last_week
      end
    end
    summary
  end

  # return the beginning_of_week of the earliest checkin record for the mentor
  def first_week
      sorted_checkins = Checkin.where(["mentor_id = ?", self.id]).order('checkin_time ASC')
      first_checkin_time = sorted_checkins.first.checkin_time
      first_week = first_checkin_time.beginning_of_week
  end

  def accumulated_hours
    acc_hours = 0
    weeks_summary.each do |week|
        acc_hours += week[:num_hours]
    end
    return acc_hours
  end
end

app/controllers/mentors_controller.rb
class MentorsController < ApplicationController
  append_before_action :authorize_super, only: [:_index]
  append_before_action :authorize_admin_or_higher, only: [:new, :create]
  append_before_action :authorize_specific_admin_or_higher, only: [:edit, :update, :destroy]
  append_before_action :authorize_specific_mentor_admin_or_higher, only: [:show, :attendances]
  append_before_action :authorize_specific_mentor, only: [:appointment, :checkin, :checkout, :checkin_loc, :checkout_loc]
  before_action :set_mentor, only: [:show, :edit, :update, :destroy, :attendances, :appointment, :checkin, :checkout, :checkin_loc, :checkout_loc]

  # GET /mentors
  # GET /mentors.json
  def _index
    @mentors = Mentor.all
    respond_to do |format|
    format.xlsx {
      response.headers[
        'Content-Disposition'
      ] = "attachment; filename=mentor_reports_#{Date.today}.xlsx"
    }
    format.html { render :_index }
  end
    Rails.logger.debug params.keys
  end

  # GET /mentors/1/details
  # show the weeks summary of the mentor
  def show
  end

  # GET /mentors/1/attendances
  # show the detailed attendances list of the mentor at a specific week
  def attendances
    @week_date = params[:week_date].nil? ? Time.current.beginning_of_week : Time.strptime(params[:week_date], "%m/%d/%Y").beginning_of_week
  end

  # GET /mentors/new
  def new
    @mentor = Mentor.new
  end

  # GET /mentors/1/edit
  def edit
  end

  # POST /mentors
  # POST /mentors.json
  def create
    @mentor = Mentor.new(mentor_params)
    respond_to do |format|
      if @mentor.save
        format.html { redirect_to @current_user, notice: "Mentor #{@mentor.name} was successfully created." }
        format.json { render :show, status: :created, location: @mentor }
      else
        format.html { render :new }
        format.json { render json: @mentor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mentors/1
  # PATCH/PUT /mentors/1.json
  def update
    respond_to do |format|
      if @mentor.update(mentor_params)
        format.html { redirect_to @current_user, notice: "Mentor #{@mentor.name} was successfully updated." }
        format.json { render :show, status: :ok, location: @mentor }
      else
        format.html { render :edit }
        format.json { render json: @mentor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mentors/1
  # DELETE /mentors/1.json
  def destroy
    @mentor.destroy
    respond_to do |format|
      format.html { redirect_to @current_user, notice: "Mentor #{@mentor.name} was successfully deleted." }
      format.json { head :no_content }
    end
  end

  def checkin_loc
  @chk_in = Checkin.new(:mentor_id => @mentor.id,
                        :school_id =>@mentor.school_id,
                        :checkin_time=> Time.current,
                        :checkin_lat => params[:la],
                        :checkin_lon => params[:lo],
                        :isValid => my_school.in_range?([@lat, @lon]),
                        :date => Date.today
                        )
  flash[:notice] = @chk_in.save ? 'Checkin succesful' : 'Something went wrong. Please try again.'
  redirect_to mentor_path
  end

def checkout_loc
    #Checks if the mentor is not signed it already. If not then won't let mentors to checkout
  if Checkin.find_by(mentor_id: @mentor.id, date: Date.today).nil?
    flash[:notice] = 'No checkin exists to checkout'
    redirect_to mentor_path
  else
   @chk_out = Checkout.new(:mentor_id => @mentor.id,
                          :school_id => @mentor.school_id,
                          :checkout_time=> Time.current,
                          :checkout_lat => params[:la],
                          :checkout_lon => params[:lo],
                          :ischeckout => true,
                          :isValid => my_school.in_range?([@lat, @lon]),
                          :date => Date.today
                          )
    flash[:notice] = @chk_out.save ? 'Checkout succesful' : 'Something went wrong. Please try again.'
    redirect_to mentor_path
    end
  end

  
  def appointment
  end


  private

    # Authorize only if the @current_user is a super or is admin of this mentor
	def authorize_specific_admin_or_higher
        return if @current_user.is_a?(Super)
        return if is_admin_of_this_mentor?
        fail_authentication_redirect
	end

	# Authorize only if the @current_user is this mentor or the admin of this mentor or a super
	def authorize_specific_mentor_admin_or_higher
    fail_authentication_redirect unless (@current_user.is_a?(Super) || is_admin_of_this_mentor? || is_this_mentor?)
  end

    # Authorize only if the @current_user is this mentor
	def authorize_specific_mentor
    fail_authentication_redirect unless is_this_mentor?
	end

    def is_this_mentor?
        this_mentor = set_mentor
        return @current_user.is_a?(Mentor) && @current_user.id == this_mentor.id
    end

    def is_admin_of_this_mentor?
        this_mentor = set_mentor
        return @current_user.is_a?(Admin) && @current_user.school.id == this_mentor.school.id
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_mentor
      @mentor = Mentor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mentor_params
      params.require(:mentor).permit(:name, :email, :school_id)
    end

  def my_school
    @school = School.find(@mentor.school_id)
  end
end

app/helpers/mentors_helper.rb
module MentorsHelper
end

app/views/mentors/_form.html.haml
= form_for @mentor do |f|
  - if @mentor.errors.any?
    #error_explanation
      %h2= "#{pluralize(@mentor.errors.count, "error")} prohibited this mentor from being saved:"
      %ul
        - @mentor.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :school_id
    = f.collection_select :school_id, School.all, :id, :name, prompt: "Select School"
  .actions
    = f.submit 'Save'

app/views/mentors/_index.html.haml
%table

  - if !@current_user.is_a? Super
    %br
    %caption= "Mentors"

  %thead
    %tr
      %th Name
      %th Email
      %th School
      %th
      %th

  %tbody
    - @mentors.each do |mentor|
      %tr
        %td= link_to mentor.name, mentor_details_path(mentor)
        %td= mentor.email
        %td= mentor.school.name
        %td= link_to 'Edit', edit_mentor_path(mentor), method: :get
        %td= link_to 'Destroy', mentor, method: :delete, data: { confirm: "Are you sure you want to remove Mentor #{mentor.name} from the database? All related checkin, checkout records will also be deleted" }

%br
= link_to 'New Mentor', new_mentor_path
%br
%br
= link_to 'Download all checkin data', mentors_path(format: :xlsx)
%br
%br
= link_to 'Delete all checkin data', cleandb_path(@current_user), data: {confirm: 'Are you sure?' }

app/views/mentors/appointment.html.haml
%html{:lang => "en"}
%br
=link_to "Check In", mentor_checkin_path , class: "btn btn block", :onclick => 'getLocation_checkin()', :remote => true
=link_to "Check Out", mentor_checkout_path, class: "btn btn block", :onclick => 'getLocation_checkout()', :remote => true

app/views/mentors/attendances.html.haml
%head

%link{:href => "/stylesheets/jquery-ui.css", :rel => "stylesheet"}/
%link{:href => "/stylesheets/style.css", :rel => "stylesheet"}/
%script{:src => "/javascripts/jquery-1.12.4.js"}
%script{:src => "/javascripts/jquery-ui.js"}
:javascript
  $( function() {
    $( "#datepicker" ).datepicker({
      firstDay: 1
    });
  } );

%body

%p
  = form_tag(@school, :method => :get, :align => "center") do
    Week of:
    %input#datepicker{:type => "text", :name => "week_date", :autocomplete => "off", :value => @week_date.strftime("%m/%d/%Y")}
    %input{:type => "submit", :value => "Select"}

%table
  %caption= 'Attendances of ' + @mentor.name + ', week of: ' + @week_date.strftime("%m/%d/%Y")

  %thead
    %tr
      %th Date
      %th Hours
      %th School
      %th Checkin Time
      %th Checkin Location
      %th Checkin Invalid Geoloc
      %th Checkout Time
      %th Checkout Location
      %th Checkout Invalid Geoloc

  %tbody
    - @mentor.attendances(@week_date).each do |check|
      - date = check[:date]
      - duration = check[:duration]
      - school_name = check[:school_name]
      - checkin = check[:checkin]
      - checkout = check[:checkout]
      %tr
        -unless @current_user.is_a? Mentor
          %td= link_to date, checkin
        -else
          %td= date
        %td= duration
        %td= school_name

        %td= checkin.checkin_time.strftime("%H:%M:%S")
        %td= "(" + checkin.checkin_lat.to_s + ", " + checkin.checkin_lon.to_s + ")"
        %td= checkin.isValid ? "-" : "invalid"

        - if checkout.nil?
          %td{:colspan => 3} Forgot to checkout
        - else
          %td= checkout.checkout_time.strftime("%H:%M:%S")
          %td= "(" + checkout.checkout_lat.to_s + ", " + checkout.checkout_lon.to_s + ")"
          %td= checkout.isValid ? "-" : "invalid"

app/views/mentors/checkin.html.haml
%p
%h1 Validate page 
%p
%h2 #{@mentor.name} successfully checked in at #{@time}

app/views/mentors/checkout.html.haml
%p
%p
%h2 #{@mentor.name} successfully checked out at #{@time}

app/views/mentors/edit.html.haml
%h1 Editing mentor

= render 'form'

app/views/mentors/new.html.haml
%h1 New mentor

= render 'form'

= link_to 'Back', @current_user

app/views/mentors/show.html.haml
%br
%br
%table
  %caption= 'Weeks Summary of ' + @mentor.name

  %thead
    %tr
      %th Week of
      %th School
      %th Total Hours
      %th Any Missed Checkout?
      %th Any Invalid Geoloc?

  %tbody
    - @mentor.weeks_summary.each do |week|
      - week_date = week[:week_date]
      - school_name = week[:school_name]
      - num_hours = week[:num_hours]
      - forgot_checkout = week[:forgot_checkout] ? "Yes" : "-"
      - anyInvalid = week[:anyInvalid] ? "Yes" : "-"
      %tr.table_row
        %td= link_to week_date, mentor_attendances_path(@mentor, :week_date => week_date)
        %td= school_name
        %td= num_hours
        %td= forgot_checkout
        %td= anyInvalid

%br
-unless @current_user.is_a? Mentor
  = link_to 'Create new checkin', new_checkin_path(:mentor_id => @mentor.id)