config/routes.rb
Rails.application.routes.draw do

  #get 'users/root'
  resources :checkins, except: [:index]
  resources :checkouts, except: [:index, :show]

  get 'schools/' => 'schools#_index', :as => 'schools'
  resources :schools, except: [:index]

  get 'supers/' => 'supers#_index', :as => 'supers'
  resources :supers, except: [:index]
  #Routes to delete all data from all checkins and checkouts table
  get '/supers/:id/cleandb', to: 'supers#cleandb',:as=> "cleandb"

  get 'admins/' => 'admins#_index', :as => 'admins'
  resources :admins, except: [:index]

  # for signed-in-user main page

  get 'mentors/' => 'mentors#_index', :as => 'mentors'
  get 'mentors/new' => 'mentors#new', :as => 'new_mentor'
  get 'mentors/:id' => 'mentors#appointment', :as => 'mentor'
  get 'mentors/:id/details' => 'mentors#show', :as => 'mentor_details'
  get 'mentors/:id/attendances' => 'mentors#attendances', :as => 'mentor_attendances'
  resources :mentors, except: [:index, :show, :new]

  #for check in and checkout @Raj
  get 'mentors/:id/get_loc', to: "mentors#get_loc"
  get '/mentors/:id/checkin', to: 'mentors#checkin', as: 'mentor_checkin'
  get '/mentors/:id/checkout', to: 'mentors#checkout', as: 'mentor_checkout'
  get '/mentors/:id/checkin_loc', to: 'mentors#checkin_loc', as: 'mentor_checkin_loc'
  get '/mentors/:id/checkout_loc', to: 'mentors#checkout_loc', as: 'mentor_checkout_loc'

  root :to => 'logins#new'

  # for google_sign_in checks
  get 'login', to: 'logins#new'
  get 'login/create', to: 'logins#create', as: :create_login

  # for log out
  delete '/logout',  to: 'logins#destroy'
  resource :session

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/school.rb
class School < ApplicationRecord
  has_one :admin, dependent: :destroy
  has_many :mentors, dependent: :destroy
  has_many :checkins, dependent: :destroy
  has_many :checkouts, dependent: :destroy

  validates :name, presence: true,  uniqueness: {case_sensitive: false}, length: {minimum: 3, maximum: 100}
  validates :address, presence: true,  uniqueness: {case_sensitive: false}, length: {minimum: 3, maximum: 300}

  # return the list of totalhours = {num_hours, forgot_checkout}
  # for all mentors in the specific week for the school
  # Assuming each mentor is associated with only one school, not many-to-many association

  def activities(week_date)
    result = []
    self.mentors.each do |mentor|
        totalhours = mentor.totalhours(week_date)
        if totalhours[:school_name] == self.name || totalhours[:school_name].nil?
          num_hours = totalhours[:num_hours]
          forgot_checkout = totalhours[:forgot_checkout]
          anyInvalid = totalhours[:anyInvalid]
          result.push({mentor:mentor, num_hours:num_hours, forgot_checkout: forgot_checkout, anyInvalid: anyInvalid})
        end
    end
    result
  end

  def self.convert_location(address)
    result = Geocoder.search(address)
    lat = result[0].latitude
    lon = result[0].longitude
    return lat,lon
  end

  def my_location
    my_geolocation = [self.lat, self.lon]
  end

  def in_range?(mentor_location)
    Geocoder::Calculations.distance_between(my_location, mentor_location) <= 0.25
  end
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  append_before_action :authorize_super, only: [:_index, :new, :edit, :create, :update, :destroy]
  append_before_action :authorize_specific_admin_or_higher, only: [:show]
  before_action :set_school, only: [:show, :edit, :update, :destroy]

  # GET /schools
  # GET /schools.json
  def _index
    @schools = School.all
  end

  # GET /schools/1
  # GET /schools/1.json
  def show
      if params[:week_date].nil?
        @week_date = Time.current
      else
        @week_date = Time.strptime(params[:week_date], "%m/%d/%Y")
      end
      @week_date = @week_date.beginning_of_week
  end

  # GET /schools/new
  def new
    @school = School.new
  end

  # GET /schools/1/edit
  def edit
  end

  # POST /schools
  # POST /schools.json
  
def create
    @school = School.new(school_params)
    @school.lat, @school.lon = School.convert_location(@school.address)
    @current_user = find_user_by_email(session[:email_address])
    respond_to do |format|
      if @school.save
        format.html { redirect_to @current_user, notice: "School '#{@school.name}' was successfully created." }
        format.json { render :show, status: :created, location: @school }
      else
        format.html { render :new }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schools/1
  # PATCH/PUT /schools/1.json
  def update
    @current_user = find_user_by_email(session[:email_address])
    @feilds = school_params
    @feilds[:lat], @feilds[:lon] = School.convert_location(@feilds[:address])
    respond_to do |format|
      if @school.update(@feilds)
        format.html { redirect_to @current_user, notice: "#{@school.name}' was successfully updated." }
        format.json { render :show, status: :ok, location: @school }
      else
        format.html { render :edit }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schools/1
  # DELETE /schools/1.json
  def destroy
    @school.destroy
    respond_to do |format|
      format.html { redirect_to @current_user, notice: "#{@school.name} was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private

    # Authorize only if the @current_user is a super or is admin of this school
	def authorize_specific_admin_or_higher
        return if @current_user.is_a?(Super)
        return if is_admin_of_this_school?
        fail_authentication_redirect
	end

    def is_admin_of_this_school?
        this_school = set_school
        return @current_user.is_a?(Admin) && @current_user.school.id == this_school.id
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_school
      @school = School.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def school_params
      params.require(:school).permit(:name, :address)
    end
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/schools/_form.html.haml
= form_for @school do |f|
  - if @school.errors.any?
    #error_explanation
      %h2= "#{pluralize(@school.errors.count, "error(s)")} prohibited this school from being saved:"
      %ul
        - @school.errors.full_messages.each do |message|
          %li= message
          %br

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :address
    = f.text_field :address
  .actions
    = f.submit 'Save'

app/views/schools/_index.html.haml
%table
  %thead
    %tr
      %th Name
      %th Address
      %th Latitude
      %th Longitude
      %th
      %th

  %tbody
    - @schools.each do |school|
      %tr
        %td= link_to school.name, school
        %td= school.address
        %td= school.lat
        %td= school.lon
        %td= link_to 'Edit', edit_school_path(school)
        %td= link_to 'Destroy', school, method: :delete, data: { confirm: "Are you sure you want to remove School #{school.name} from the database? All related admin, mentor, checkin, checkout records will also be deleted" }

%br

= link_to 'New School', new_school_path

app/views/schools/edit.html.haml
%h1 Editing school

= render 'form'

= link_to 'Show', @school
\|
= link_to 'Back', @current_user

app/views/schools/index.html.haml
%h1 Listing schools

%table
  %thead
    %tr
      %th Name
      %th Admin
      %th Address
      %th Latitude
      %th Longitude
      %th
      %th
      %th

  %tbody
    - @schools.each do |school|
      %tr
        %td= school.name
        %td= school.admin.name
        %td= school.address
        %td= school.latitude
        %td= school.longitude
        %td= link_to 'Show', school
        %td= link_to 'Edit', edit_school_path(school)
        %td= link_to 'Destroy', school, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New School', new_school_path

app/views/schools/new.html.haml
%h1 New school

= render 'form'

= link_to 'Back', @current_user

app/views/schools/show.html.haml
%head

%link{:href => "/stylesheets/jquery-ui.css", :rel => "stylesheet"}/
%link{:href => "/stylesheets/style.css", :rel => "stylesheet"}/
%script{:src => "/javascripts/jquery-1.12.4.js"}
%script{:src => "/javascripts/jquery-ui.js"}
:javascript
  $( function() {
    $( "#datepicker" ).datepicker({
      firstDay: 1
    });
  } );

%body

%p
  = form_tag(@school, :method => :get, :align => "center") do
    Week of:
    %input#datepicker{:type => "text", :name => "week_date", :autocomplete => "off", :value => @week_date.strftime("%m/%d/%Y")}
    %input{:type => "submit", :value => "Select"}

%p
  = link_to 'Create New Mentor', new_mentor_path

%table
  %caption= @school.name + ' Activity, week of: ' + @week_date.strftime("%m/%d/%Y")

  %thead
    %tr
      %th Mentor
      %th Week Hours
      %th Any Missed Checkout?
      %th Any Invalid Geoloc?
      %th Accumulated Hours
      %th
      %th

  %tbody
    - @school.activities(@week_date).each do |r|
      - mentor = r[:mentor]
      - num_hours = r[:num_hours]
      - forgot_checkout = r[:forgot_checkout] ? "Yes" : "-"
      - anyInvalid = r[:anyInvalid] ? "Yes" : "-"
      - acc_hours = mentor.accumulated_hours
      %tr.table_row
        %td= link_to mentor.name, mentor_details_path(mentor)
        %td= num_hours
        %td= forgot_checkout
        %td= anyInvalid
        %td= acc_hours
        %td= link_to 'Edit', edit_mentor_path(mentor), method: :get
        %td= link_to 'Destroy', mentor, method: :delete, data: { confirm: "Are you sure you want to remove Mentor #{mentor.name} from the database? All related checkin, checkout records will also be deleted" }