config/routes.rb
Rails.application.routes.draw do

  #get 'users/root'
  resources :checkins, except: [:index]
  resources :checkouts, except: [:index, :show]

  get 'schools/' => 'schools#_index', :as => 'schools'
  resources :schools, except: [:index]

  get 'supers/' => 'supers#_index', :as => 'supers'
  resources :supers, except: [:index]
  #Routes to delete all data from all checkins and checkouts table
  get '/supers/:id/cleandb', to: 'supers#cleandb',:as=> "cleandb"

  get 'admins/' => 'admins#_index', :as => 'admins'
  resources :admins, except: [:index]

  # for signed-in-user main page

  get 'mentors/' => 'mentors#_index', :as => 'mentors'
  get 'mentors/new' => 'mentors#new', :as => 'new_mentor'
  get 'mentors/:id' => 'mentors#appointment', :as => 'mentor'
  get 'mentors/:id/details' => 'mentors#show', :as => 'mentor_details'
  get 'mentors/:id/attendances' => 'mentors#attendances', :as => 'mentor_attendances'
  resources :mentors, except: [:index, :show, :new]

  #for check in and checkout @Raj
  get 'mentors/:id/get_loc', to: "mentors#get_loc"
  get '/mentors/:id/checkin', to: 'mentors#checkin', as: 'mentor_checkin'
  get '/mentors/:id/checkout', to: 'mentors#checkout', as: 'mentor_checkout'
  get '/mentors/:id/checkin_loc', to: 'mentors#checkin_loc', as: 'mentor_checkin_loc'
  get '/mentors/:id/checkout_loc', to: 'mentors#checkout_loc', as: 'mentor_checkout_loc'

  root :to => 'logins#new'

  # for google_sign_in checks
  get 'login', to: 'logins#new'
  get 'login/create', to: 'logins#create', as: :create_login

  # for log out
  delete '/logout',  to: 'logins#destroy'
  resource :session

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/checkin.rb
require 'csv'
class Checkin < ApplicationRecord
	belongs_to :mentor
	belongs_to :school

	def school
			School.find(self.school_id)
	end

	# find and return the corresponding checkout,
	# which is on the same day as checkin and occurs after checkin_time
	# assuming that only at most one checkin and one checkout each day

	def correspond_checkout
		checkin_time = self.checkin_time
		checkout = Checkout.where("mentor_id = :mentor_id and school_id = :school_id
                and checkout_time >= :checkin_time
                and checkout_time >= :same_day_start
                and checkout_time <= :same_day_end",
															:mentor_id => self.mentor_id,
															:school_id => self.school_id                ,
															:checkin_time => checkin_time,
															:same_day_start => checkin_time.beginning_of_day,
															:same_day_end => checkin_time.end_of_day).first
	end
end

app/controllers/checkins_controller.rb
class CheckinsController < ApplicationController
  append_before_action :authorize_admin_or_higher, only: [:new, :create]
  append_before_action :authorize_specific_admin_or_higher, only: [:show, :edit, :update, :destroy]
  before_action :set_checkin, only: [:show, :edit, :update, :destroy]

  # GET /checkins/1
  # GET /checkins/1.json
  def show
    @checkout = @checkin.correspond_checkout
  end

  # GET /checkins/new
  def new
    @checkin = Checkin.new
    @mentor_id = params[:mentor_id]
    unless @mentor_id.nil?
        mentor = Mentor.find(params[:mentor_id])
        school = mentor.school
        @checkin.mentor = mentor
        @checkin.school_id = school.id
        @checkin.checkin_lat = school.lat
        @checkin.checkin_lon = school.lon
        @checkin.isValid = true
    end
  end

  # GET /checkins/1/edit
  def edit
    @mentor_id = @checkin.mentor_id
  end

  # POST /checkins
  # POST /checkins.json
  def create
    @checkin = Checkin.new(checkin_params)
    @checkin.checkin_lat = @checkin.school.lat
    @checkin.checkin_lon = @checkin.school.lon
    unless params[:mentor_id].nil?
        @checkin.mentor = Mentor.find(params[:mentor_id])
    end

    respond_to do |format|
      @checkin.date = @checkin.checkin_time.to_date
      if @checkin.save
        format.html { redirect_to @checkin, notice: 'Checkin was successfully created.' }
        format.json { render :show, status: :created, location: @checkin }
      else
        format.html { render :new }
        format.json { render json: @checkin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /checkins/1
  # PATCH/PUT /checkins/1.json
  def update
    @checkin.checkin_lat = @checkin.school.lat
    @checkin.checkin_lon = @checkin.school.lon
    unless params[:mentor_id].nil?
        @checkin.mentor = Mentor.find(params[:mentor_id])
    end

    respond_to do |format|
      @checkin.date = @checkin.checkin_time.to_date
      if @checkin.update(checkin_params)
        format.html { redirect_to @checkin, notice: 'Checkin was successfully updated.' }
        format.json { render :show, status: :ok, location: @checkin }
      else
        format.html { render :edit }
        format.json { render json: @checkin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /checkins/1
  # DELETE /checkins/1.json
  def destroy
    @checkin.destroy
    respond_to do |format|
      format.html { redirect_to checkins_url, notice: 'Checkin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Authorize only if the @current_user is a super or is admin of the mentor of this checkin
	def authorize_specific_admin_or_higher
        return if @current_user.is_a?(Super)
        return if is_admin_of_this_checkin?
        fail_authentication_redirect
	end

    def is_admin_of_this_checkin?
        this_checkin = set_checkin
        return @current_user.is_a?(Admin) && @current_user.school.id == this_checkin.mentor.school.id
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_checkin
      @checkin = Checkin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def checkin_params
      params.require(:checkin).permit(:checkin_time, :checkin_lat, :checkin_lon, :mentor_id, :school_id, :isValid)
    end
end

app/helpers/checkins_helper.rb
module CheckinsHelper
end

app/views/checkins/_form.html.haml
= form_for @checkin do |f|
  - if @checkin.errors.any?
    #error_explanation
      %h2= "#{pluralize(@checkin.errors.count, "error")} prohibited this checkin from being saved:"
      %ul
        - @checkin.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :checkin_time
    = f.datetime_select :checkin_time
  .field
    = f.label :school_id
    = f.collection_select :school_id, School.all, :id, :name, prompt: "Select School"
  .field
    = f.label :isValid
    = f.select :isValid, [['True', true], ['False', false]]
  = f.hidden_field :mentor_id, value: @mentor_id
  .actions
    = f.submit 'Save'

app/views/checkins/edit.html.haml
%h1
  = "Editing checkin " + ("of " + @checkin.mentor.name) unless @checkin.mentor.nil?
%br

= render 'form'

= link_to 'Back', @checkin

app/views/checkins/new.html.haml
%h1
  = "New checkin " + ("of " + @checkin.mentor.name) unless @checkin.mentor.nil?
%br

= render 'form'

-#= link_to 'Back', checkins_path

app/views/checkins/show.html.haml
%p#notice= notice

%h2 Check In
%p{:style => "text-indent: 40px"}
  %b Mentor:
  = @checkin.mentor.name
%p{:style => "text-indent: 40px"}
  %b Time:
  = @checkin.checkin_time.strftime("%m/%d/%Y %H:%M:%S")
%p{:style => "text-indent: 40px"}
  %b Latitude:
  = @checkin.checkin_lat
%p{:style => "text-indent: 40px"}
  %b Longitude:
  = @checkin.checkin_lon
%p{:style => "text-indent: 40px"}
  %b Location:
  = @checkin.school.name
%p{:style => "text-indent: 40px"}
  %b isValid:
  = @checkin.isValid
%p{:style => "text-indent: 40px"}
  = link_to 'Edit Check In', edit_checkin_path(@checkin)


%br
%br
%h2 Check Out

- if @checkout.nil?
  %p{:style => "text-indent: 40px"}
    = link_to 'Create New Checkout', new_checkout_path(:correspond_checkin_id => @checkin.id)
- else
  %p{:style => "text-indent: 40px"}
    %b Mentor:
    = @checkout.mentor.name
  %p{:style => "text-indent: 40px"}
    %b Time:
    = @checkout.checkout_time.strftime("%m/%d/%Y %H:%M:%S")
  %p{:style => "text-indent: 40px"}
    %b Latitude:
    = @checkout.checkout_lat
  %p{:style => "text-indent: 40px"}
    %b Longitude:
    = @checkout.checkout_lon
  %p{:style => "text-indent: 40px"}
    %b Location:
    = @checkout.school.name
  %p{:style => "text-indent: 40px"}
    %b isValid:
    = @checkout.isValid
  %p{:style => "text-indent: 40px"}
    = link_to 'Edit Check Out', edit_checkout_path(@checkout)

%br
= link_to 'Back', mentor_attendances_path(@checkin.mentor)